<?php

namespace EntityBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
	public function forum(){
		$em = $this->getEntityManager();
		$connection = $em->getConnection();
		$statement = $connection->prepare("SELECT forum.message, forum.date , user.username
                                           FROM forum LEFT JOIN user ON forum.user_id = user.id"
	    );
		$statement->execute();
		$results = $statement->fetchAll();

		return $results;
	}

}
