<?php

namespace EntityBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
	public function userMessages($user_id){
		$em = $this->getEntityManager();
		$connection = $em->getConnection();
		$statement = $connection->prepare("SELECT user.username, message.id, message.sent_to_id, message.sent_from_id, message.text_message, message.id, user_profile.lastname, 
			user_profile.firstname, user_profile.company, user_profile.country, message.created_at, message.status
			FROM message
			LEFT JOIN user_profile ON  message.sent_from_id = user_profile.user_id
			LEFT JOIN user ON message.sent_from_id = user.id
			WHERE message.sent_to_id = ".$user_id.";"
	    );
		$statement->execute();
		$results = $statement->fetchAll();

		return $results;
	}

	public function sentMessages($user_id){
		$em = $this->getEntityManager();
		$connection = $em->getConnection();
		$statement = $connection->prepare("SELECT user.username, message.id, message.sent_to_id, message.sent_from_id, message.text_message, message.id, user_profile.lastname, 
						user_profile.firstname, user_profile.company, user_profile.country, message.created_at, message.status
						FROM message
						LEFT JOIN user_profile ON  message.sent_from_id = user_profile.user_id
						LEFT JOIN user ON message.sent_from_id = user.id
						WHERE message.sent_from_id = ".$user_id.";"
	    );
		$statement->execute();
		$results = $statement->fetchAll();

		return $results;
	}
}