<?php

namespace EntityBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function Users(){
		$em = $this->getEntityManager();
		$connection = $em->getConnection();
		$statement = $connection->prepare("SELECT user.id, user.username, user_profile.firstname, user_profile.lastname, user_profile.phone, user_profile.passport, user_profile.company, user_profile.country, user_profile.city, user_profile.address, user.created_at FROM
				user_profile
				LEFT JOIN user ON user_profile.user_id = user.id;"
           );
		$statement->execute();
		$results = $statement->fetchAll();

		return $results;
	}
}
